### PR TITLE
Updated PFID DNN model files trained for Run3Summer21

### PR DESCRIPTION
**Pull request by valsdav**
New models and scaler configuration for PFID with DNN algo.
They are needed for the CMSSW_12_2_0 PR.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/36243#issuecomment-980477372

**Comment by perrotta** [comment]
@smuzaffar the tests that show crashes were started automatically after reco signature, and they are due to the lack of the accompanying PRs https://github.com/cms-sw/cmssw/pull/36243 and https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/24
I'm going to merge this together with the other two PRs

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
