### PR TITLE
XML weights for latest Spring15 photon IDs

### PR DESCRIPTION
**Pull request by lgray**
@degano Please queue these for 7[4-6]X. For 74X they are needed for the MiniAOD reprocessing campaign.

@slava77

### CODE REVIEW

**Comment by ghost** [comment]
@davidlange6

**Comment by ghost** [comment]
@lgray Merged here: https://github.com/cms-sw/cmsdist/pull/1720 for 76X.
As usual check that's all good with the next IB (2015-08-06-1100) and then I'll merge it also for the previous release cycles.

**Comment by lgray** [comment]
Thanks @degano!

FYI: I'm just doing forward/back ports to 75X and 74X, since 75X -> 76X
automatic merging is fine for the time being.

Best,
-Lindsey

On Thu, Aug 6, 2015 at 10:48 AM, Alessandro Degano <notifications@github.com

**Comment by lgray** [comment]
@degano Everything looks OK in the 1100 76X IB, please backport!

**Pull request merged**
