### PR TITLE
Added the .xml to .root version of RunIII Winter22 photon MVA ID weights

### PR DESCRIPTION
**Pull request by Prasant1993**
Added the TMVA BDT weights converted from .xml to .root by "convertXMLToGBRForestROOT" trained in RunIII Winter22 GJet MC campaign

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by rappoccio** [comment]
+1

Signatures are made on the code PR, assuming they are also signing here.

**Comment by rappoccio** [comment]
please merge

**Comment by mandrenguyen** [comment]
+1
for posterity

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
this was needed to go with https://github.com/cms-sw/cmssw/pull/39927 ,  I will include it in cmsdist and force build an IB

**Pull request merged**
