### PR TITLE
Add 25ns V2 IDs for photons

### PR DESCRIPTION
**Pull request by lgray**
@degano We now have the 25ns V2 IDs in time for the MiniAOD reprocessing. Please queue this for 76X, then 75X & 74X if all goes well, as usual.

I'll put the code PRs in CMSSW once everything is in the IB.

@ikrav @cmkuo

### CODE REVIEW

**Comment by ghost** [comment]
@lgray https://github.com/cms-sw/cmsdist/pull/1744

**Comment by lgray** [comment]
@degano thanks!

**Comment by lgray** [comment]
@degano Everything looks OK (from the slc7 build, slc6 build is baking), please push this into 75X and 74X.

**Comment by ghost** [comment]
@lgray done here:
https://github.com/cms-sw/cmsdist/pull/1747
and here:
https://github.com/cms-sw/cmsdist/pull/1746

**Comment by lgray** [comment]
@degano thanks!

**Pull request merged**
