### PR TITLE
XGBoost Photon MVA files version 2

### PR DESCRIPTION
**Pull request by smorovic**
Including newest model files retrained on Winter2024 HGG sample and 14_0_X.

This is the final version intended for inclusion of MVA diphoton HLT Path with CMSSW_14_0_X.
Pull requests for CMSSW master and 14_0_X will be opened as well to update default parameters and add unit tests.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/44719

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@jfernan2, as you signed https://github.com/cms-sw/cmssw/pull/44719,  can you please sign also this one (corresponding external update)?

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
