### PR TITLE
XGBoost Photon HLT model files

### PR DESCRIPTION
**Pull request by smorovic**
Initial version of XGBoost model files for XGBoost based Photon MVA for HLT.
Trained on XGBoost v1.7.5

For CMSSW PR:
https://github.com/cms-sw/cmssw/pull/44473

Which will be updated accordingly to use these files by default and in an unit test.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/44473

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovilela** [comment]
@smorovic @mandrenguyen @jfernan2 
Please clarify if the model files are meant to be used only for HLT.
I ask @cms-sw/reconstruction-l2 to sign such that they are aware of the model files being included under [RecoEgamma-PhotonIdentification](https://github.com/cms-data/RecoEgamma-PhotonIdentification)

**Comment by smorovic** [comment]
@antoniovilela
Yes, they are trained on photons and egamma variables reconstructed at HLT, so they are only applicable in this case.

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
