### PR TITLE
First version of BDT based BH tagger training files

### PR DESCRIPTION
**Pull request by jainshilpi**
First commit of the training files needed by the PR #36901

### CODE REVIEW

**Comment by jpata** [comment]
note: probably the .xml.gz file should be removed, and this PR rebased to erase it from history and keep the git repo size minimal.

**Comment by jpata** [comment]
@jainshilpi could you please rebase this PR to remove the .xml.gz from history? just to keep the size minimal

**Comment by jainshilpi** [comment]
> @jainshilpi could you please rebase this PR to remove the .xml.gz from history? just to keep the size minimal

@jpata - sorry I meant to do it much before. Its done now. Thanks for the reminder.

**Comment by jpata** [comment]
thanks, but this isn't fully correct: for the rebase, the commit history should contain only one commit, and it must be force pushed. Otherwise the deleted file still exists in git history.

See here "overview of rebase" for more details:
https://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by jainshilpi** [comment]
> thanks, but this isn't fully correct: for the rebase, the commit history should contain only one commit, and it must be force pushed. Otherwise the deleted file still exists in git history.
> 
> See here "overview of rebase" for more details: https://cms-sw.github.io/tutorial-resolve-conflicts.html

I hope the last one takes care of removing this from the history as well. many thanks to @valsdav for helping with this.

**Comment by jpata** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/36901

**Comment by tvami** [comment]
@perrotta @qliphy I think this needs to be merged since https://github.com/cms-sw/cmssw/pull/36901 was merged

**Comment by tvami** [comment]
or @smuzaffar 

it's currently stopping other PRs, see for example:
https://github.com/cms-sw/cmssw/pull/37130#issuecomment-1058629919

**Comment by qliphy** [comment]
+1
tested with [#36901](https://github.com/cms-sw/cmssw/pull/36901)

**Comment by qliphy** [comment]
merge

**Pull request merged**
