### PR TITLE
Added Photon MVA V2 weight files and gzipped all Run 2 weight files

### PR DESCRIPTION
**Pull request by guitargeek**
Besides adding the Photon MVA V2 weight files here, I gzipped all Run 2 weight files, as for the electrons https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/9.

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by slava77** [comment]
most of the older file names were  ```photon_general_MVA_```
The new additions are ```EgammaPhoId_``` is there a good reason to change the style?

There is 94X in the file names already. Is it really necessary to also have a new directory with  Fall17_94X ?

**Comment by guitargeek** [comment]
I guess there is no good reason to change the style. You want something more consistent, now that we rename everything anyway with `.gz`? At least I removed the Fall17_94X directory.

**Comment by slava77** [comment]
why not photon_general as a prefix to match what existed before?
Perhaps I miss the context and the "photon general" referred to the non-GED photons.

Technically, ```RecoEgamma/PhotonIdentification``` should be enough to denote the purpose. The rest of the name repeating that it's a photon is perhaps not needed.
I'm open for discussion to converge on something descriptive and less random for every update.

**Comment by guitargeek** [comment]
They are all for GED photons here, the `photon_general` should just mean that they pass no specific trigger and they are for general analysis use, and not only for one specific analysis like H -> gg. 

Maybe the following naming scheme is fine?

```
RecoEgamma/PhotonIdentification/data/MVA/2015/25ns_EE_V2.weights.xml.gz
```
If there are not two different IDs for different bunch spacing, the first prefix in the file name is dropped.

Edit: actually MVA instead of MVAWeightFiles is just fine. There is the word `weights` in the file suffix.

**Comment by guitargeek** [comment]
I just realized this scheme so you can check what it looks like. Now these tiny effective area files look kinda out of place, maybe they should better be in cmssw? Then we would at least not get questions anymore where they are :)

**Comment by slava77** [comment]
I'm not sure that changing Fall2017 to just 2017 is generally clear.
IIUC, these correspond to the campaign name strings, not to the years when the files were derived.
It can become pretty confusing if there are, say, Spring2019 and Fall2019

**Comment by slava77** [comment]
about the effective areas, most recent ones are in cmssw
https://github.com/cms-sw/cmssw/tree/master/RecoEgamma/PhotonIdentification/data/Fall17
so, perhaps the PHYS14 are OK then to be (back) to cmssw

**Comment by guitargeek** [comment]
Ah yes, that's where these seasons come from! Right, let's leave them in the names.

**Comment by smuzaffar** [comment]
@slava77 , is this ready for integration?

**Comment by guitargeek** [comment]
There is no rush, I still have to wait for the green light from Egamma to do the corresponding cmssw PR anyway.

**Comment by slava77** [comment]
+1

I think that it's worth to proceed with a cmsdist PR

**Comment by mrodozov** [comment]
+externals

**Pull request merged**
