### PR TITLE
Added model files for egamma PFid DNN

### PR DESCRIPTION
**Pull request by valsdav**
The new folder Photon_PFID_dnn contains both the tensorflow model files (.pb) and the configs files for the Egamma PFid DNN.
The .txt config files contain both the list of variables to be used for each model and their scaling configuration.

This is related to the PR cms-sw/cmssw#35403 for CMSSW_12_1_0.

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/35403#issuecomment-938889201
- please merge concurrently with https://github.com/cms-sw/cmssw/pull/35403

**Comment by jpata** [comment]
Just to make sure we do the steps of coupled PRs correctly, could this PR with just new files be merged?

**Comment by perrotta** [comment]
+1
- Only new files are added, which will be needed by #35403

**Comment by perrotta** [comment]
@smuzaffar I can even merge this one myself (similar to https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/23# but for photons rather than electron), but maybe you also want to have a look...

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
new files only, bot has opened https://github.com/cms-sw/cmsdist/pull/7389 which can be merged before  cms-sw/cmssw#35403

**Pull request merged**
